# Generated by Django 5.1.4 on 2024-12-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
