# Generated by Django 5.1.4 on 2024-12-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Student Information'},
        ),
        migrations.AlterModelOptions(
            name='loginform',
            options={'verbose_name_plural': 'Sign-Up Student Account'},
        ),
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='student.home')),
            ],
            options={
                'verbose_name_plural': 'Sign-In Student Account',
            },
        ),
    ]
