# Generated by Django 5.1.4 on 2024-12-28 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_home_options_alter_loginform_options_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='student.loginform'),
        ),
    ]
