# Generated by Django 5.1.4 on 2024-12-28 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentid_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='student_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Login_student', to='student.loginform'),
        ),
    ]
