# Generated by Django 5.1.4 on 2024-12-31 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_home_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student_options', models.CharField(choices=[('Summary', 'Summary'), ('Keywords', 'Keywords'), ('Full-Text', 'Full-Text')], max_length=30)),
            ],
        ),
    ]
