# Generated by Django 5.1.4 on 2025-01-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_uploadfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name_plural': 'File Upload'},
        ),
    ]
