# Generated by Django 5.1.4 on 2025-01-03 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_uploadfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='student_options',
            field=models.CharField(choices=[('Summary', 'Summary'), ('Keywords', 'Keywords')], max_length=30),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'pptx'])]),
        ),
    ]
